# Generated by Django 5.2.4 on 2025-07-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_options_task_order'),
        ('todo', '0002_task_priority_alter_task_posted_at_alter_task_title'),
    ]

    operations = [
    ]
